version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: tic-tac-two-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: tic-tac-two-frontend
    depends_on:
      - backend